### ISSUE TITLE
Allow the app verification by the main author

### ISSUE THREAD

**Issue by prodrigestivill** [flathub/org.radare.iaito#39]
Hello @barthalion,

This flatpak application is packaged by me (@prodrigestivill) with close contact with the oficial main author of the app.
In `my flathub` section I can see this app and I can initiate the verification process, but given the current plan for the future additions in flathub I think it would be better if this process is initiated by the main developer itself.

Is that possible? Is this how is actually intended to be done?
I have no problem to have my permissions to demoted to merge-only and his permissions upgraded to owner, if this is how is setup internally.

Also the main author of the app has 2 github accounts, both are the same person: @radare @trufae
To verify those users, the full list of the @radareorg team can be found [here](https://github.com/orgs/radareorg/people).
As well as his own approval in the flathub submission request: flathub/flathub#3545

As I understand allowing to verify the app by any of those 2 would do the trick.
@radare @trufae: answer here if you require to be one in particular.

Thanks in advance,

Pau

**Comment by trufae** [comment]
both accounts are fine to me, @radare sounds like more "official", but im currently comiting as trufae,
