### ISSUE TITLE
Please remove usages of branch property from manifests

### ISSUE THREAD

**Issue by bbhtt** [flathub/org.radare.iaito#63]
https://github.com/flathub/org.radare.iaito/blob/5b6b3e09e18a749bf62a818d79bd0232ecd448ef/org.radare.iaito.yaml#L217

should be tag or commit or tag+commit

**Comment by prodrigestivill** [comment]
Ok, thanks for the report.
PR in progress.

When this was added, we had a discussion in the matrix channel, and I remember that even the decision at that time was to accept `branch`, not everybody was onboard.

In any case, thanks for the update, I just changed to use flatpak external checker with JSON.

Thanks
